version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
      POSTGRES_DB: myapp_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "13000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: password
    depends_on:
      - db